#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

# runApplication setFields
# runApplication decomposePar
# runApplication $(getApplication)
runApplication buoyantPimpleFoam_noU 

# runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
